
version: 2

models:
    - name: employees
      description: "A sample data employees"
      # columns:
      #     - name: id
      #       description: "The primary key for this table"
      #       tests:
      #           - unique
      #           - not_null

    - name: transactions
      description: "A sample data transactions"
      # columns:
      #     - name: id
      #       description: "The primary key for this table"
      #       tests:
      #           - unique
      #           - not_null
